### ISSUE TITLE
REST API Integration

### ISSUE THREAD

**Issue by Ubaid-Rahman** [stashh-labs/stashh#29]
### Description

I want to integrate my app with NFT marketplace, Opensea api is the best option that comes in mind, but it only allows to fetch data, you can not directly send anything from app to opensea, and also its on etherium, I just wanted anything that we can directly send images from app to marketplace where it can be converted to NFT if there is ample transaction fee inside accounts wallet.

### Justification

I am working on development of an app that involves people uploading images and videos, I want that when one person clicks on create NFT, it gives a form to fill, like title, Description etc, and then on submit it takes you to stashh original site with whole form pre-filled and the user just have to integrate wallet to create it. Also user can view his/her NFTs on app and also the bids as well

**Comment by scarylooking** [comment]
Thanks for the suggestion @Ubaid-Rahman. 

We are not looking to implement minting via an API at this time because...

-  the same functionality can be achieved by programmatically interfacing with a Stashh listing contract via the CLI
- there are technical and security considerations that make this infeasible for us currently
- minting via an API would be open to abuse
